//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ModelManCalCbo", "TBL_JEF_TBL_USR_FK", "TBL_USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelManCalCbo.TBL_USUARIO), "TBL_JEFE", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelManCalCbo.TBL_JEFE), true)]
[assembly: EdmRelationshipAttribute("ModelManCalCbo", "TBL_VEN_TBL_USR_FK", "TBL_USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ModelManCalCbo.TBL_USUARIO), "TBL_VENDEDOR", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ModelManCalCbo.TBL_VENDEDOR), true)]

#endregion

namespace ModelManCalCbo
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EntitiesManCalCbo : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EntitiesManCalCbo usando la cadena de conexión encontrada en la sección 'EntitiesManCalCbo' del archivo de configuración de la aplicación.
        /// </summary>
        public EntitiesManCalCbo() : base("name=EntitiesManCalCbo", "EntitiesManCalCbo")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntitiesManCalCbo.
        /// </summary>
        public EntitiesManCalCbo(string connectionString) : base(connectionString, "EntitiesManCalCbo")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntitiesManCalCbo.
        /// </summary>
        public EntitiesManCalCbo(EntityConnection connection) : base(connection, "EntitiesManCalCbo")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_COTIZACION> TBL_TIPO_COTIZACION
        {
            get
            {
                if ((_TBL_TIPO_COTIZACION == null))
                {
                    _TBL_TIPO_COTIZACION = base.CreateObjectSet<TBL_TIPO_COTIZACION>("TBL_TIPO_COTIZACION");
                }
                return _TBL_TIPO_COTIZACION;
            }
        }
        private ObjectSet<TBL_TIPO_COTIZACION> _TBL_TIPO_COTIZACION;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_JEFE> TBL_JEFE
        {
            get
            {
                if ((_TBL_JEFE == null))
                {
                    _TBL_JEFE = base.CreateObjectSet<TBL_JEFE>("TBL_JEFE");
                }
                return _TBL_JEFE;
            }
        }
        private ObjectSet<TBL_JEFE> _TBL_JEFE;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_VENDEDOR> TBL_VENDEDOR
        {
            get
            {
                if ((_TBL_VENDEDOR == null))
                {
                    _TBL_VENDEDOR = base.CreateObjectSet<TBL_VENDEDOR>("TBL_VENDEDOR");
                }
                return _TBL_VENDEDOR;
            }
        }
        private ObjectSet<TBL_VENDEDOR> _TBL_VENDEDOR;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_USUARIO> TBL_USUARIO
        {
            get
            {
                if ((_TBL_USUARIO == null))
                {
                    _TBL_USUARIO = base.CreateObjectSet<TBL_USUARIO>("TBL_USUARIO");
                }
                return _TBL_USUARIO;
            }
        }
        private ObjectSet<TBL_USUARIO> _TBL_USUARIO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_TARIFA> TBL_TIPO_TARIFA
        {
            get
            {
                if ((_TBL_TIPO_TARIFA == null))
                {
                    _TBL_TIPO_TARIFA = base.CreateObjectSet<TBL_TIPO_TARIFA>("TBL_TIPO_TARIFA");
                }
                return _TBL_TIPO_TARIFA;
            }
        }
        private ObjectSet<TBL_TIPO_TARIFA> _TBL_TIPO_TARIFA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_TRABAJO> TBL_TIPO_TRABAJO
        {
            get
            {
                if ((_TBL_TIPO_TRABAJO == null))
                {
                    _TBL_TIPO_TRABAJO = base.CreateObjectSet<TBL_TIPO_TRABAJO>("TBL_TIPO_TRABAJO");
                }
                return _TBL_TIPO_TRABAJO;
            }
        }
        private ObjectSet<TBL_TIPO_TRABAJO> _TBL_TIPO_TRABAJO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_FACTURACION> TBL_TIPO_FACTURACION
        {
            get
            {
                if ((_TBL_TIPO_FACTURACION == null))
                {
                    _TBL_TIPO_FACTURACION = base.CreateObjectSet<TBL_TIPO_FACTURACION>("TBL_TIPO_FACTURACION");
                }
                return _TBL_TIPO_FACTURACION;
            }
        }
        private ObjectSet<TBL_TIPO_FACTURACION> _TBL_TIPO_FACTURACION;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_FPAGO_FACTURA> TBL_TIPO_FPAGO_FACTURA
        {
            get
            {
                if ((_TBL_TIPO_FPAGO_FACTURA == null))
                {
                    _TBL_TIPO_FPAGO_FACTURA = base.CreateObjectSet<TBL_TIPO_FPAGO_FACTURA>("TBL_TIPO_FPAGO_FACTURA");
                }
                return _TBL_TIPO_FPAGO_FACTURA;
            }
        }
        private ObjectSet<TBL_TIPO_FPAGO_FACTURA> _TBL_TIPO_FPAGO_FACTURA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_PLAZO_ENTREGA> TBL_TIPO_PLAZO_ENTREGA
        {
            get
            {
                if ((_TBL_TIPO_PLAZO_ENTREGA == null))
                {
                    _TBL_TIPO_PLAZO_ENTREGA = base.CreateObjectSet<TBL_TIPO_PLAZO_ENTREGA>("TBL_TIPO_PLAZO_ENTREGA");
                }
                return _TBL_TIPO_PLAZO_ENTREGA;
            }
        }
        private ObjectSet<TBL_TIPO_PLAZO_ENTREGA> _TBL_TIPO_PLAZO_ENTREGA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_GARANTIA> TBL_TIPO_GARANTIA
        {
            get
            {
                if ((_TBL_TIPO_GARANTIA == null))
                {
                    _TBL_TIPO_GARANTIA = base.CreateObjectSet<TBL_TIPO_GARANTIA>("TBL_TIPO_GARANTIA");
                }
                return _TBL_TIPO_GARANTIA;
            }
        }
        private ObjectSet<TBL_TIPO_GARANTIA> _TBL_TIPO_GARANTIA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_LUGAR_EJEC> TBL_TIPO_LUGAR_EJEC
        {
            get
            {
                if ((_TBL_TIPO_LUGAR_EJEC == null))
                {
                    _TBL_TIPO_LUGAR_EJEC = base.CreateObjectSet<TBL_TIPO_LUGAR_EJEC>("TBL_TIPO_LUGAR_EJEC");
                }
                return _TBL_TIPO_LUGAR_EJEC;
            }
        }
        private ObjectSet<TBL_TIPO_LUGAR_EJEC> _TBL_TIPO_LUGAR_EJEC;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_LUGAR_ENTREGA> TBL_TIPO_LUGAR_ENTREGA
        {
            get
            {
                if ((_TBL_TIPO_LUGAR_ENTREGA == null))
                {
                    _TBL_TIPO_LUGAR_ENTREGA = base.CreateObjectSet<TBL_TIPO_LUGAR_ENTREGA>("TBL_TIPO_LUGAR_ENTREGA");
                }
                return _TBL_TIPO_LUGAR_ENTREGA;
            }
        }
        private ObjectSet<TBL_TIPO_LUGAR_ENTREGA> _TBL_TIPO_LUGAR_ENTREGA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_VALI_GARANTIA> TBL_TIPO_VALI_GARANTIA
        {
            get
            {
                if ((_TBL_TIPO_VALI_GARANTIA == null))
                {
                    _TBL_TIPO_VALI_GARANTIA = base.CreateObjectSet<TBL_TIPO_VALI_GARANTIA>("TBL_TIPO_VALI_GARANTIA");
                }
                return _TBL_TIPO_VALI_GARANTIA;
            }
        }
        private ObjectSet<TBL_TIPO_VALI_GARANTIA> _TBL_TIPO_VALI_GARANTIA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_REGION> TBL_REGION
        {
            get
            {
                if ((_TBL_REGION == null))
                {
                    _TBL_REGION = base.CreateObjectSet<TBL_REGION>("TBL_REGION");
                }
                return _TBL_REGION;
            }
        }
        private ObjectSet<TBL_REGION> _TBL_REGION;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_TIPO_ENVIO> TBL_TIPO_ENVIO
        {
            get
            {
                if ((_TBL_TIPO_ENVIO == null))
                {
                    _TBL_TIPO_ENVIO = base.CreateObjectSet<TBL_TIPO_ENVIO>("TBL_TIPO_ENVIO");
                }
                return _TBL_TIPO_ENVIO;
            }
        }
        private ObjectSet<TBL_TIPO_ENVIO> _TBL_TIPO_ENVIO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_LUGAR> TBL_LUGAR
        {
            get
            {
                if ((_TBL_LUGAR == null))
                {
                    _TBL_LUGAR = base.CreateObjectSet<TBL_LUGAR>("TBL_LUGAR");
                }
                return _TBL_LUGAR;
            }
        }
        private ObjectSet<TBL_LUGAR> _TBL_LUGAR;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_COTIZACION. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_COTIZACION(TBL_TIPO_COTIZACION tBL_TIPO_COTIZACION)
        {
            base.AddObject("TBL_TIPO_COTIZACION", tBL_TIPO_COTIZACION);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_JEFE. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_JEFE(TBL_JEFE tBL_JEFE)
        {
            base.AddObject("TBL_JEFE", tBL_JEFE);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_VENDEDOR. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_VENDEDOR(TBL_VENDEDOR tBL_VENDEDOR)
        {
            base.AddObject("TBL_VENDEDOR", tBL_VENDEDOR);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_USUARIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_USUARIO(TBL_USUARIO tBL_USUARIO)
        {
            base.AddObject("TBL_USUARIO", tBL_USUARIO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_TARIFA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_TARIFA(TBL_TIPO_TARIFA tBL_TIPO_TARIFA)
        {
            base.AddObject("TBL_TIPO_TARIFA", tBL_TIPO_TARIFA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_TRABAJO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_TRABAJO(TBL_TIPO_TRABAJO tBL_TIPO_TRABAJO)
        {
            base.AddObject("TBL_TIPO_TRABAJO", tBL_TIPO_TRABAJO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_FACTURACION. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_FACTURACION(TBL_TIPO_FACTURACION tBL_TIPO_FACTURACION)
        {
            base.AddObject("TBL_TIPO_FACTURACION", tBL_TIPO_FACTURACION);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_FPAGO_FACTURA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_FPAGO_FACTURA(TBL_TIPO_FPAGO_FACTURA tBL_TIPO_FPAGO_FACTURA)
        {
            base.AddObject("TBL_TIPO_FPAGO_FACTURA", tBL_TIPO_FPAGO_FACTURA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_PLAZO_ENTREGA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_PLAZO_ENTREGA(TBL_TIPO_PLAZO_ENTREGA tBL_TIPO_PLAZO_ENTREGA)
        {
            base.AddObject("TBL_TIPO_PLAZO_ENTREGA", tBL_TIPO_PLAZO_ENTREGA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_GARANTIA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_GARANTIA(TBL_TIPO_GARANTIA tBL_TIPO_GARANTIA)
        {
            base.AddObject("TBL_TIPO_GARANTIA", tBL_TIPO_GARANTIA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_LUGAR_EJEC. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_LUGAR_EJEC(TBL_TIPO_LUGAR_EJEC tBL_TIPO_LUGAR_EJEC)
        {
            base.AddObject("TBL_TIPO_LUGAR_EJEC", tBL_TIPO_LUGAR_EJEC);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_LUGAR_ENTREGA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_LUGAR_ENTREGA(TBL_TIPO_LUGAR_ENTREGA tBL_TIPO_LUGAR_ENTREGA)
        {
            base.AddObject("TBL_TIPO_LUGAR_ENTREGA", tBL_TIPO_LUGAR_ENTREGA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_VALI_GARANTIA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_VALI_GARANTIA(TBL_TIPO_VALI_GARANTIA tBL_TIPO_VALI_GARANTIA)
        {
            base.AddObject("TBL_TIPO_VALI_GARANTIA", tBL_TIPO_VALI_GARANTIA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_REGION. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_REGION(TBL_REGION tBL_REGION)
        {
            base.AddObject("TBL_REGION", tBL_REGION);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_TIPO_ENVIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_TIPO_ENVIO(TBL_TIPO_ENVIO tBL_TIPO_ENVIO)
        {
            base.AddObject("TBL_TIPO_ENVIO", tBL_TIPO_ENVIO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_LUGAR. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_LUGAR(TBL_LUGAR tBL_LUGAR)
        {
            base.AddObject("TBL_LUGAR", tBL_LUGAR);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_JEFE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_JEFE : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_JEFE.
        /// </summary>
        /// <param name="jEF_ID">Valor inicial de la propiedad JEF_ID.</param>
        /// <param name="jEF_AREA">Valor inicial de la propiedad JEF_AREA.</param>
        /// <param name="uSR_ID">Valor inicial de la propiedad USR_ID.</param>
        public static TBL_JEFE CreateTBL_JEFE(global::System.Decimal jEF_ID, global::System.String jEF_AREA, global::System.Decimal uSR_ID)
        {
            TBL_JEFE tBL_JEFE = new TBL_JEFE();
            tBL_JEFE.JEF_ID = jEF_ID;
            tBL_JEFE.JEF_AREA = jEF_AREA;
            tBL_JEFE.USR_ID = uSR_ID;
            return tBL_JEFE;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal JEF_ID
        {
            get
            {
                return _JEF_ID;
            }
            set
            {
                if (_JEF_ID != value)
                {
                    OnJEF_IDChanging(value);
                    ReportPropertyChanging("JEF_ID");
                    _JEF_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JEF_ID");
                    OnJEF_IDChanged();
                }
            }
        }
        private global::System.Decimal _JEF_ID;
        partial void OnJEF_IDChanging(global::System.Decimal value);
        partial void OnJEF_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String JEF_AREA
        {
            get
            {
                return _JEF_AREA;
            }
            set
            {
                OnJEF_AREAChanging(value);
                ReportPropertyChanging("JEF_AREA");
                _JEF_AREA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("JEF_AREA");
                OnJEF_AREAChanged();
            }
        }
        private global::System.String _JEF_AREA;
        partial void OnJEF_AREAChanging(global::System.String value);
        partial void OnJEF_AREAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_ID
        {
            get
            {
                return _USR_ID;
            }
            set
            {
                OnUSR_IDChanging(value);
                ReportPropertyChanging("USR_ID");
                _USR_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_ID");
                OnUSR_IDChanged();
            }
        }
        private global::System.Decimal _USR_ID;
        partial void OnUSR_IDChanging(global::System.Decimal value);
        partial void OnUSR_IDChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelManCalCbo", "TBL_JEF_TBL_USR_FK", "TBL_USUARIO")]
        public TBL_USUARIO TBL_USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_JEF_TBL_USR_FK", "TBL_USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_JEF_TBL_USR_FK", "TBL_USUARIO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBL_USUARIO> TBL_USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_JEF_TBL_USR_FK", "TBL_USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_JEF_TBL_USR_FK", "TBL_USUARIO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_LUGAR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_LUGAR : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_LUGAR.
        /// </summary>
        /// <param name="lUG_ID">Valor inicial de la propiedad LUG_ID.</param>
        /// <param name="lUG_NOMBRE">Valor inicial de la propiedad LUG_NOMBRE.</param>
        /// <param name="lUG_DIVISA">Valor inicial de la propiedad LUG_DIVISA.</param>
        public static TBL_LUGAR CreateTBL_LUGAR(global::System.Decimal lUG_ID, global::System.String lUG_NOMBRE, global::System.String lUG_DIVISA)
        {
            TBL_LUGAR tBL_LUGAR = new TBL_LUGAR();
            tBL_LUGAR.LUG_ID = lUG_ID;
            tBL_LUGAR.LUG_NOMBRE = lUG_NOMBRE;
            tBL_LUGAR.LUG_DIVISA = lUG_DIVISA;
            return tBL_LUGAR;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LUG_ID
        {
            get
            {
                return _LUG_ID;
            }
            set
            {
                if (_LUG_ID != value)
                {
                    OnLUG_IDChanging(value);
                    ReportPropertyChanging("LUG_ID");
                    _LUG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LUG_ID");
                    OnLUG_IDChanged();
                }
            }
        }
        private global::System.Decimal _LUG_ID;
        partial void OnLUG_IDChanging(global::System.Decimal value);
        partial void OnLUG_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUG_NOMBRE
        {
            get
            {
                return _LUG_NOMBRE;
            }
            set
            {
                OnLUG_NOMBREChanging(value);
                ReportPropertyChanging("LUG_NOMBRE");
                _LUG_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUG_NOMBRE");
                OnLUG_NOMBREChanged();
            }
        }
        private global::System.String _LUG_NOMBRE;
        partial void OnLUG_NOMBREChanging(global::System.String value);
        partial void OnLUG_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LUG_DIVISA
        {
            get
            {
                return _LUG_DIVISA;
            }
            set
            {
                OnLUG_DIVISAChanging(value);
                ReportPropertyChanging("LUG_DIVISA");
                _LUG_DIVISA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LUG_DIVISA");
                OnLUG_DIVISAChanged();
            }
        }
        private global::System.String _LUG_DIVISA;
        partial void OnLUG_DIVISAChanging(global::System.String value);
        partial void OnLUG_DIVISAChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_REGION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_REGION : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_REGION.
        /// </summary>
        /// <param name="rEG_ID">Valor inicial de la propiedad REG_ID.</param>
        /// <param name="rEG_NOMBRE">Valor inicial de la propiedad REG_NOMBRE.</param>
        /// <param name="rEG_PRECIO">Valor inicial de la propiedad REG_PRECIO.</param>
        public static TBL_REGION CreateTBL_REGION(global::System.Decimal rEG_ID, global::System.String rEG_NOMBRE, global::System.Decimal rEG_PRECIO)
        {
            TBL_REGION tBL_REGION = new TBL_REGION();
            tBL_REGION.REG_ID = rEG_ID;
            tBL_REGION.REG_NOMBRE = rEG_NOMBRE;
            tBL_REGION.REG_PRECIO = rEG_PRECIO;
            return tBL_REGION;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal REG_ID
        {
            get
            {
                return _REG_ID;
            }
            set
            {
                if (_REG_ID != value)
                {
                    OnREG_IDChanging(value);
                    ReportPropertyChanging("REG_ID");
                    _REG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("REG_ID");
                    OnREG_IDChanged();
                }
            }
        }
        private global::System.Decimal _REG_ID;
        partial void OnREG_IDChanging(global::System.Decimal value);
        partial void OnREG_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String REG_NOMBRE
        {
            get
            {
                return _REG_NOMBRE;
            }
            set
            {
                OnREG_NOMBREChanging(value);
                ReportPropertyChanging("REG_NOMBRE");
                _REG_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("REG_NOMBRE");
                OnREG_NOMBREChanged();
            }
        }
        private global::System.String _REG_NOMBRE;
        partial void OnREG_NOMBREChanging(global::System.String value);
        partial void OnREG_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal REG_PRECIO
        {
            get
            {
                return _REG_PRECIO;
            }
            set
            {
                OnREG_PRECIOChanging(value);
                ReportPropertyChanging("REG_PRECIO");
                _REG_PRECIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("REG_PRECIO");
                OnREG_PRECIOChanged();
            }
        }
        private global::System.Decimal _REG_PRECIO;
        partial void OnREG_PRECIOChanging(global::System.Decimal value);
        partial void OnREG_PRECIOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_COTIZACION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_COTIZACION : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_COTIZACION.
        /// </summary>
        /// <param name="tC_ID">Valor inicial de la propiedad TC_ID.</param>
        /// <param name="tC_NOMBRE">Valor inicial de la propiedad TC_NOMBRE.</param>
        /// <param name="tC_UN_ID">Valor inicial de la propiedad TC_UN_ID.</param>
        public static TBL_TIPO_COTIZACION CreateTBL_TIPO_COTIZACION(global::System.Decimal tC_ID, global::System.String tC_NOMBRE, global::System.String tC_UN_ID)
        {
            TBL_TIPO_COTIZACION tBL_TIPO_COTIZACION = new TBL_TIPO_COTIZACION();
            tBL_TIPO_COTIZACION.TC_ID = tC_ID;
            tBL_TIPO_COTIZACION.TC_NOMBRE = tC_NOMBRE;
            tBL_TIPO_COTIZACION.TC_UN_ID = tC_UN_ID;
            return tBL_TIPO_COTIZACION;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TC_ID
        {
            get
            {
                return _TC_ID;
            }
            set
            {
                if (_TC_ID != value)
                {
                    OnTC_IDChanging(value);
                    ReportPropertyChanging("TC_ID");
                    _TC_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TC_ID");
                    OnTC_IDChanged();
                }
            }
        }
        private global::System.Decimal _TC_ID;
        partial void OnTC_IDChanging(global::System.Decimal value);
        partial void OnTC_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TC_NOMBRE
        {
            get
            {
                return _TC_NOMBRE;
            }
            set
            {
                OnTC_NOMBREChanging(value);
                ReportPropertyChanging("TC_NOMBRE");
                _TC_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TC_NOMBRE");
                OnTC_NOMBREChanged();
            }
        }
        private global::System.String _TC_NOMBRE;
        partial void OnTC_NOMBREChanging(global::System.String value);
        partial void OnTC_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TC_UN_ID
        {
            get
            {
                return _TC_UN_ID;
            }
            set
            {
                OnTC_UN_IDChanging(value);
                ReportPropertyChanging("TC_UN_ID");
                _TC_UN_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TC_UN_ID");
                OnTC_UN_IDChanged();
            }
        }
        private global::System.String _TC_UN_ID;
        partial void OnTC_UN_IDChanging(global::System.String value);
        partial void OnTC_UN_IDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_ENVIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_ENVIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_ENVIO.
        /// </summary>
        /// <param name="tEN_ID">Valor inicial de la propiedad TEN_ID.</param>
        /// <param name="tEN_NOMBRE">Valor inicial de la propiedad TEN_NOMBRE.</param>
        public static TBL_TIPO_ENVIO CreateTBL_TIPO_ENVIO(global::System.Decimal tEN_ID, global::System.String tEN_NOMBRE)
        {
            TBL_TIPO_ENVIO tBL_TIPO_ENVIO = new TBL_TIPO_ENVIO();
            tBL_TIPO_ENVIO.TEN_ID = tEN_ID;
            tBL_TIPO_ENVIO.TEN_NOMBRE = tEN_NOMBRE;
            return tBL_TIPO_ENVIO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TEN_ID
        {
            get
            {
                return _TEN_ID;
            }
            set
            {
                if (_TEN_ID != value)
                {
                    OnTEN_IDChanging(value);
                    ReportPropertyChanging("TEN_ID");
                    _TEN_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TEN_ID");
                    OnTEN_IDChanged();
                }
            }
        }
        private global::System.Decimal _TEN_ID;
        partial void OnTEN_IDChanging(global::System.Decimal value);
        partial void OnTEN_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEN_NOMBRE
        {
            get
            {
                return _TEN_NOMBRE;
            }
            set
            {
                OnTEN_NOMBREChanging(value);
                ReportPropertyChanging("TEN_NOMBRE");
                _TEN_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TEN_NOMBRE");
                OnTEN_NOMBREChanged();
            }
        }
        private global::System.String _TEN_NOMBRE;
        partial void OnTEN_NOMBREChanging(global::System.String value);
        partial void OnTEN_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_FACTURACION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_FACTURACION : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_FACTURACION.
        /// </summary>
        /// <param name="tF_ID">Valor inicial de la propiedad TF_ID.</param>
        /// <param name="tF_NOMBRE">Valor inicial de la propiedad TF_NOMBRE.</param>
        public static TBL_TIPO_FACTURACION CreateTBL_TIPO_FACTURACION(global::System.Decimal tF_ID, global::System.String tF_NOMBRE)
        {
            TBL_TIPO_FACTURACION tBL_TIPO_FACTURACION = new TBL_TIPO_FACTURACION();
            tBL_TIPO_FACTURACION.TF_ID = tF_ID;
            tBL_TIPO_FACTURACION.TF_NOMBRE = tF_NOMBRE;
            return tBL_TIPO_FACTURACION;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TF_ID
        {
            get
            {
                return _TF_ID;
            }
            set
            {
                if (_TF_ID != value)
                {
                    OnTF_IDChanging(value);
                    ReportPropertyChanging("TF_ID");
                    _TF_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TF_ID");
                    OnTF_IDChanged();
                }
            }
        }
        private global::System.Decimal _TF_ID;
        partial void OnTF_IDChanging(global::System.Decimal value);
        partial void OnTF_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TF_NOMBRE
        {
            get
            {
                return _TF_NOMBRE;
            }
            set
            {
                OnTF_NOMBREChanging(value);
                ReportPropertyChanging("TF_NOMBRE");
                _TF_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TF_NOMBRE");
                OnTF_NOMBREChanged();
            }
        }
        private global::System.String _TF_NOMBRE;
        partial void OnTF_NOMBREChanging(global::System.String value);
        partial void OnTF_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_FPAGO_FACTURA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_FPAGO_FACTURA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_FPAGO_FACTURA.
        /// </summary>
        /// <param name="tFPF_ID">Valor inicial de la propiedad TFPF_ID.</param>
        /// <param name="tFPF_NOMBRE">Valor inicial de la propiedad TFPF_NOMBRE.</param>
        public static TBL_TIPO_FPAGO_FACTURA CreateTBL_TIPO_FPAGO_FACTURA(global::System.Decimal tFPF_ID, global::System.String tFPF_NOMBRE)
        {
            TBL_TIPO_FPAGO_FACTURA tBL_TIPO_FPAGO_FACTURA = new TBL_TIPO_FPAGO_FACTURA();
            tBL_TIPO_FPAGO_FACTURA.TFPF_ID = tFPF_ID;
            tBL_TIPO_FPAGO_FACTURA.TFPF_NOMBRE = tFPF_NOMBRE;
            return tBL_TIPO_FPAGO_FACTURA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TFPF_ID
        {
            get
            {
                return _TFPF_ID;
            }
            set
            {
                if (_TFPF_ID != value)
                {
                    OnTFPF_IDChanging(value);
                    ReportPropertyChanging("TFPF_ID");
                    _TFPF_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TFPF_ID");
                    OnTFPF_IDChanged();
                }
            }
        }
        private global::System.Decimal _TFPF_ID;
        partial void OnTFPF_IDChanging(global::System.Decimal value);
        partial void OnTFPF_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TFPF_NOMBRE
        {
            get
            {
                return _TFPF_NOMBRE;
            }
            set
            {
                OnTFPF_NOMBREChanging(value);
                ReportPropertyChanging("TFPF_NOMBRE");
                _TFPF_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TFPF_NOMBRE");
                OnTFPF_NOMBREChanged();
            }
        }
        private global::System.String _TFPF_NOMBRE;
        partial void OnTFPF_NOMBREChanging(global::System.String value);
        partial void OnTFPF_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_GARANTIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_GARANTIA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_GARANTIA.
        /// </summary>
        /// <param name="tG_ID">Valor inicial de la propiedad TG_ID.</param>
        /// <param name="tG_NOMBRE">Valor inicial de la propiedad TG_NOMBRE.</param>
        public static TBL_TIPO_GARANTIA CreateTBL_TIPO_GARANTIA(global::System.Decimal tG_ID, global::System.String tG_NOMBRE)
        {
            TBL_TIPO_GARANTIA tBL_TIPO_GARANTIA = new TBL_TIPO_GARANTIA();
            tBL_TIPO_GARANTIA.TG_ID = tG_ID;
            tBL_TIPO_GARANTIA.TG_NOMBRE = tG_NOMBRE;
            return tBL_TIPO_GARANTIA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TG_ID
        {
            get
            {
                return _TG_ID;
            }
            set
            {
                if (_TG_ID != value)
                {
                    OnTG_IDChanging(value);
                    ReportPropertyChanging("TG_ID");
                    _TG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TG_ID");
                    OnTG_IDChanged();
                }
            }
        }
        private global::System.Decimal _TG_ID;
        partial void OnTG_IDChanging(global::System.Decimal value);
        partial void OnTG_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TG_NOMBRE
        {
            get
            {
                return _TG_NOMBRE;
            }
            set
            {
                OnTG_NOMBREChanging(value);
                ReportPropertyChanging("TG_NOMBRE");
                _TG_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TG_NOMBRE");
                OnTG_NOMBREChanged();
            }
        }
        private global::System.String _TG_NOMBRE;
        partial void OnTG_NOMBREChanging(global::System.String value);
        partial void OnTG_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_LUGAR_EJEC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_LUGAR_EJEC : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_LUGAR_EJEC.
        /// </summary>
        /// <param name="tLEJ_ID">Valor inicial de la propiedad TLEJ_ID.</param>
        /// <param name="tLEJ_NOMBRE">Valor inicial de la propiedad TLEJ_NOMBRE.</param>
        public static TBL_TIPO_LUGAR_EJEC CreateTBL_TIPO_LUGAR_EJEC(global::System.Decimal tLEJ_ID, global::System.String tLEJ_NOMBRE)
        {
            TBL_TIPO_LUGAR_EJEC tBL_TIPO_LUGAR_EJEC = new TBL_TIPO_LUGAR_EJEC();
            tBL_TIPO_LUGAR_EJEC.TLEJ_ID = tLEJ_ID;
            tBL_TIPO_LUGAR_EJEC.TLEJ_NOMBRE = tLEJ_NOMBRE;
            return tBL_TIPO_LUGAR_EJEC;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TLEJ_ID
        {
            get
            {
                return _TLEJ_ID;
            }
            set
            {
                if (_TLEJ_ID != value)
                {
                    OnTLEJ_IDChanging(value);
                    ReportPropertyChanging("TLEJ_ID");
                    _TLEJ_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TLEJ_ID");
                    OnTLEJ_IDChanged();
                }
            }
        }
        private global::System.Decimal _TLEJ_ID;
        partial void OnTLEJ_IDChanging(global::System.Decimal value);
        partial void OnTLEJ_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TLEJ_NOMBRE
        {
            get
            {
                return _TLEJ_NOMBRE;
            }
            set
            {
                OnTLEJ_NOMBREChanging(value);
                ReportPropertyChanging("TLEJ_NOMBRE");
                _TLEJ_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TLEJ_NOMBRE");
                OnTLEJ_NOMBREChanged();
            }
        }
        private global::System.String _TLEJ_NOMBRE;
        partial void OnTLEJ_NOMBREChanging(global::System.String value);
        partial void OnTLEJ_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_LUGAR_ENTREGA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_LUGAR_ENTREGA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_LUGAR_ENTREGA.
        /// </summary>
        /// <param name="tLE_ID">Valor inicial de la propiedad TLE_ID.</param>
        /// <param name="tLE_NOMBRE">Valor inicial de la propiedad TLE_NOMBRE.</param>
        public static TBL_TIPO_LUGAR_ENTREGA CreateTBL_TIPO_LUGAR_ENTREGA(global::System.Decimal tLE_ID, global::System.String tLE_NOMBRE)
        {
            TBL_TIPO_LUGAR_ENTREGA tBL_TIPO_LUGAR_ENTREGA = new TBL_TIPO_LUGAR_ENTREGA();
            tBL_TIPO_LUGAR_ENTREGA.TLE_ID = tLE_ID;
            tBL_TIPO_LUGAR_ENTREGA.TLE_NOMBRE = tLE_NOMBRE;
            return tBL_TIPO_LUGAR_ENTREGA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TLE_ID
        {
            get
            {
                return _TLE_ID;
            }
            set
            {
                if (_TLE_ID != value)
                {
                    OnTLE_IDChanging(value);
                    ReportPropertyChanging("TLE_ID");
                    _TLE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TLE_ID");
                    OnTLE_IDChanged();
                }
            }
        }
        private global::System.Decimal _TLE_ID;
        partial void OnTLE_IDChanging(global::System.Decimal value);
        partial void OnTLE_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TLE_NOMBRE
        {
            get
            {
                return _TLE_NOMBRE;
            }
            set
            {
                OnTLE_NOMBREChanging(value);
                ReportPropertyChanging("TLE_NOMBRE");
                _TLE_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TLE_NOMBRE");
                OnTLE_NOMBREChanged();
            }
        }
        private global::System.String _TLE_NOMBRE;
        partial void OnTLE_NOMBREChanging(global::System.String value);
        partial void OnTLE_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_PLAZO_ENTREGA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_PLAZO_ENTREGA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_PLAZO_ENTREGA.
        /// </summary>
        /// <param name="tPE_ID">Valor inicial de la propiedad TPE_ID.</param>
        /// <param name="tPE_NOMBRE">Valor inicial de la propiedad TPE_NOMBRE.</param>
        public static TBL_TIPO_PLAZO_ENTREGA CreateTBL_TIPO_PLAZO_ENTREGA(global::System.Decimal tPE_ID, global::System.String tPE_NOMBRE)
        {
            TBL_TIPO_PLAZO_ENTREGA tBL_TIPO_PLAZO_ENTREGA = new TBL_TIPO_PLAZO_ENTREGA();
            tBL_TIPO_PLAZO_ENTREGA.TPE_ID = tPE_ID;
            tBL_TIPO_PLAZO_ENTREGA.TPE_NOMBRE = tPE_NOMBRE;
            return tBL_TIPO_PLAZO_ENTREGA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TPE_ID
        {
            get
            {
                return _TPE_ID;
            }
            set
            {
                if (_TPE_ID != value)
                {
                    OnTPE_IDChanging(value);
                    ReportPropertyChanging("TPE_ID");
                    _TPE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TPE_ID");
                    OnTPE_IDChanged();
                }
            }
        }
        private global::System.Decimal _TPE_ID;
        partial void OnTPE_IDChanging(global::System.Decimal value);
        partial void OnTPE_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TPE_NOMBRE
        {
            get
            {
                return _TPE_NOMBRE;
            }
            set
            {
                OnTPE_NOMBREChanging(value);
                ReportPropertyChanging("TPE_NOMBRE");
                _TPE_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TPE_NOMBRE");
                OnTPE_NOMBREChanged();
            }
        }
        private global::System.String _TPE_NOMBRE;
        partial void OnTPE_NOMBREChanging(global::System.String value);
        partial void OnTPE_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_TARIFA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_TARIFA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_TARIFA.
        /// </summary>
        /// <param name="tT_ID">Valor inicial de la propiedad TT_ID.</param>
        /// <param name="tT_NOMBRE">Valor inicial de la propiedad TT_NOMBRE.</param>
        public static TBL_TIPO_TARIFA CreateTBL_TIPO_TARIFA(global::System.Decimal tT_ID, global::System.String tT_NOMBRE)
        {
            TBL_TIPO_TARIFA tBL_TIPO_TARIFA = new TBL_TIPO_TARIFA();
            tBL_TIPO_TARIFA.TT_ID = tT_ID;
            tBL_TIPO_TARIFA.TT_NOMBRE = tT_NOMBRE;
            return tBL_TIPO_TARIFA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TT_ID
        {
            get
            {
                return _TT_ID;
            }
            set
            {
                if (_TT_ID != value)
                {
                    OnTT_IDChanging(value);
                    ReportPropertyChanging("TT_ID");
                    _TT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TT_ID");
                    OnTT_IDChanged();
                }
            }
        }
        private global::System.Decimal _TT_ID;
        partial void OnTT_IDChanging(global::System.Decimal value);
        partial void OnTT_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TT_NOMBRE
        {
            get
            {
                return _TT_NOMBRE;
            }
            set
            {
                OnTT_NOMBREChanging(value);
                ReportPropertyChanging("TT_NOMBRE");
                _TT_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TT_NOMBRE");
                OnTT_NOMBREChanged();
            }
        }
        private global::System.String _TT_NOMBRE;
        partial void OnTT_NOMBREChanging(global::System.String value);
        partial void OnTT_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_TRABAJO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_TRABAJO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_TRABAJO.
        /// </summary>
        /// <param name="tTR_ID">Valor inicial de la propiedad TTR_ID.</param>
        /// <param name="tTR_NOMBRE">Valor inicial de la propiedad TTR_NOMBRE.</param>
        /// <param name="tTR_UN_ID">Valor inicial de la propiedad TTR_UN_ID.</param>
        /// <param name="tTR_FORMATO">Valor inicial de la propiedad TTR_FORMATO.</param>
        public static TBL_TIPO_TRABAJO CreateTBL_TIPO_TRABAJO(global::System.Decimal tTR_ID, global::System.String tTR_NOMBRE, global::System.String tTR_UN_ID, global::System.String tTR_FORMATO)
        {
            TBL_TIPO_TRABAJO tBL_TIPO_TRABAJO = new TBL_TIPO_TRABAJO();
            tBL_TIPO_TRABAJO.TTR_ID = tTR_ID;
            tBL_TIPO_TRABAJO.TTR_NOMBRE = tTR_NOMBRE;
            tBL_TIPO_TRABAJO.TTR_UN_ID = tTR_UN_ID;
            tBL_TIPO_TRABAJO.TTR_FORMATO = tTR_FORMATO;
            return tBL_TIPO_TRABAJO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TTR_ID
        {
            get
            {
                return _TTR_ID;
            }
            set
            {
                if (_TTR_ID != value)
                {
                    OnTTR_IDChanging(value);
                    ReportPropertyChanging("TTR_ID");
                    _TTR_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TTR_ID");
                    OnTTR_IDChanged();
                }
            }
        }
        private global::System.Decimal _TTR_ID;
        partial void OnTTR_IDChanging(global::System.Decimal value);
        partial void OnTTR_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TTR_NOMBRE
        {
            get
            {
                return _TTR_NOMBRE;
            }
            set
            {
                OnTTR_NOMBREChanging(value);
                ReportPropertyChanging("TTR_NOMBRE");
                _TTR_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TTR_NOMBRE");
                OnTTR_NOMBREChanged();
            }
        }
        private global::System.String _TTR_NOMBRE;
        partial void OnTTR_NOMBREChanging(global::System.String value);
        partial void OnTTR_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TTR_UN_ID
        {
            get
            {
                return _TTR_UN_ID;
            }
            set
            {
                OnTTR_UN_IDChanging(value);
                ReportPropertyChanging("TTR_UN_ID");
                _TTR_UN_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TTR_UN_ID");
                OnTTR_UN_IDChanged();
            }
        }
        private global::System.String _TTR_UN_ID;
        partial void OnTTR_UN_IDChanging(global::System.String value);
        partial void OnTTR_UN_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TTR_FORMATO
        {
            get
            {
                return _TTR_FORMATO;
            }
            set
            {
                OnTTR_FORMATOChanging(value);
                ReportPropertyChanging("TTR_FORMATO");
                _TTR_FORMATO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TTR_FORMATO");
                OnTTR_FORMATOChanged();
            }
        }
        private global::System.String _TTR_FORMATO;
        partial void OnTTR_FORMATOChanging(global::System.String value);
        partial void OnTTR_FORMATOChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_TIPO_VALI_GARANTIA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_TIPO_VALI_GARANTIA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_TIPO_VALI_GARANTIA.
        /// </summary>
        /// <param name="tVG_ID">Valor inicial de la propiedad TVG_ID.</param>
        /// <param name="tVG_NOMBRE">Valor inicial de la propiedad TVG_NOMBRE.</param>
        public static TBL_TIPO_VALI_GARANTIA CreateTBL_TIPO_VALI_GARANTIA(global::System.Decimal tVG_ID, global::System.String tVG_NOMBRE)
        {
            TBL_TIPO_VALI_GARANTIA tBL_TIPO_VALI_GARANTIA = new TBL_TIPO_VALI_GARANTIA();
            tBL_TIPO_VALI_GARANTIA.TVG_ID = tVG_ID;
            tBL_TIPO_VALI_GARANTIA.TVG_NOMBRE = tVG_NOMBRE;
            return tBL_TIPO_VALI_GARANTIA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TVG_ID
        {
            get
            {
                return _TVG_ID;
            }
            set
            {
                if (_TVG_ID != value)
                {
                    OnTVG_IDChanging(value);
                    ReportPropertyChanging("TVG_ID");
                    _TVG_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TVG_ID");
                    OnTVG_IDChanged();
                }
            }
        }
        private global::System.Decimal _TVG_ID;
        partial void OnTVG_IDChanging(global::System.Decimal value);
        partial void OnTVG_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TVG_NOMBRE
        {
            get
            {
                return _TVG_NOMBRE;
            }
            set
            {
                OnTVG_NOMBREChanging(value);
                ReportPropertyChanging("TVG_NOMBRE");
                _TVG_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TVG_NOMBRE");
                OnTVG_NOMBREChanged();
            }
        }
        private global::System.String _TVG_NOMBRE;
        partial void OnTVG_NOMBREChanging(global::System.String value);
        partial void OnTVG_NOMBREChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_USUARIO.
        /// </summary>
        /// <param name="uSR_ID">Valor inicial de la propiedad USR_ID.</param>
        /// <param name="uSR_NOMBRE">Valor inicial de la propiedad USR_NOMBRE.</param>
        /// <param name="uSR_APPAT">Valor inicial de la propiedad USR_APPAT.</param>
        /// <param name="uSR_APMAT">Valor inicial de la propiedad USR_APMAT.</param>
        /// <param name="uSR_USRPC">Valor inicial de la propiedad USR_USRPC.</param>
        /// <param name="uSR_PWD">Valor inicial de la propiedad USR_PWD.</param>
        /// <param name="uSR_PERFIL">Valor inicial de la propiedad USR_PERFIL.</param>
        /// <param name="uSR_ESTADO">Valor inicial de la propiedad USR_ESTADO.</param>
        public static TBL_USUARIO CreateTBL_USUARIO(global::System.Decimal uSR_ID, global::System.String uSR_NOMBRE, global::System.String uSR_APPAT, global::System.String uSR_APMAT, global::System.String uSR_USRPC, global::System.String uSR_PWD, global::System.Decimal uSR_PERFIL, global::System.Decimal uSR_ESTADO)
        {
            TBL_USUARIO tBL_USUARIO = new TBL_USUARIO();
            tBL_USUARIO.USR_ID = uSR_ID;
            tBL_USUARIO.USR_NOMBRE = uSR_NOMBRE;
            tBL_USUARIO.USR_APPAT = uSR_APPAT;
            tBL_USUARIO.USR_APMAT = uSR_APMAT;
            tBL_USUARIO.USR_USRPC = uSR_USRPC;
            tBL_USUARIO.USR_PWD = uSR_PWD;
            tBL_USUARIO.USR_PERFIL = uSR_PERFIL;
            tBL_USUARIO.USR_ESTADO = uSR_ESTADO;
            return tBL_USUARIO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_ID
        {
            get
            {
                return _USR_ID;
            }
            set
            {
                if (_USR_ID != value)
                {
                    OnUSR_IDChanging(value);
                    ReportPropertyChanging("USR_ID");
                    _USR_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USR_ID");
                    OnUSR_IDChanged();
                }
            }
        }
        private global::System.Decimal _USR_ID;
        partial void OnUSR_IDChanging(global::System.Decimal value);
        partial void OnUSR_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_NOMBRE
        {
            get
            {
                return _USR_NOMBRE;
            }
            set
            {
                OnUSR_NOMBREChanging(value);
                ReportPropertyChanging("USR_NOMBRE");
                _USR_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_NOMBRE");
                OnUSR_NOMBREChanged();
            }
        }
        private global::System.String _USR_NOMBRE;
        partial void OnUSR_NOMBREChanging(global::System.String value);
        partial void OnUSR_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_APPAT
        {
            get
            {
                return _USR_APPAT;
            }
            set
            {
                OnUSR_APPATChanging(value);
                ReportPropertyChanging("USR_APPAT");
                _USR_APPAT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_APPAT");
                OnUSR_APPATChanged();
            }
        }
        private global::System.String _USR_APPAT;
        partial void OnUSR_APPATChanging(global::System.String value);
        partial void OnUSR_APPATChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_APMAT
        {
            get
            {
                return _USR_APMAT;
            }
            set
            {
                OnUSR_APMATChanging(value);
                ReportPropertyChanging("USR_APMAT");
                _USR_APMAT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_APMAT");
                OnUSR_APMATChanged();
            }
        }
        private global::System.String _USR_APMAT;
        partial void OnUSR_APMATChanging(global::System.String value);
        partial void OnUSR_APMATChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_USRPC
        {
            get
            {
                return _USR_USRPC;
            }
            set
            {
                OnUSR_USRPCChanging(value);
                ReportPropertyChanging("USR_USRPC");
                _USR_USRPC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_USRPC");
                OnUSR_USRPCChanged();
            }
        }
        private global::System.String _USR_USRPC;
        partial void OnUSR_USRPCChanging(global::System.String value);
        partial void OnUSR_USRPCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_PWD
        {
            get
            {
                return _USR_PWD;
            }
            set
            {
                OnUSR_PWDChanging(value);
                ReportPropertyChanging("USR_PWD");
                _USR_PWD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_PWD");
                OnUSR_PWDChanged();
            }
        }
        private global::System.String _USR_PWD;
        partial void OnUSR_PWDChanging(global::System.String value);
        partial void OnUSR_PWDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_PERFIL
        {
            get
            {
                return _USR_PERFIL;
            }
            set
            {
                OnUSR_PERFILChanging(value);
                ReportPropertyChanging("USR_PERFIL");
                _USR_PERFIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_PERFIL");
                OnUSR_PERFILChanged();
            }
        }
        private global::System.Decimal _USR_PERFIL;
        partial void OnUSR_PERFILChanging(global::System.Decimal value);
        partial void OnUSR_PERFILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_ESTADO
        {
            get
            {
                return _USR_ESTADO;
            }
            set
            {
                OnUSR_ESTADOChanging(value);
                ReportPropertyChanging("USR_ESTADO");
                _USR_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_ESTADO");
                OnUSR_ESTADOChanged();
            }
        }
        private global::System.Decimal _USR_ESTADO;
        partial void OnUSR_ESTADOChanging(global::System.Decimal value);
        partial void OnUSR_ESTADOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelManCalCbo", "TBL_JEF_TBL_USR_FK", "TBL_JEFE")]
        public EntityCollection<TBL_JEFE> TBL_JEFE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBL_JEFE>("ModelManCalCbo.TBL_JEF_TBL_USR_FK", "TBL_JEFE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBL_JEFE>("ModelManCalCbo.TBL_JEF_TBL_USR_FK", "TBL_JEFE", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelManCalCbo", "TBL_VEN_TBL_USR_FK", "TBL_VENDEDOR")]
        public EntityCollection<TBL_VENDEDOR> TBL_VENDEDOR
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TBL_VENDEDOR>("ModelManCalCbo.TBL_VEN_TBL_USR_FK", "TBL_VENDEDOR");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TBL_VENDEDOR>("ModelManCalCbo.TBL_VEN_TBL_USR_FK", "TBL_VENDEDOR", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCalCbo", Name="TBL_VENDEDOR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_VENDEDOR : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_VENDEDOR.
        /// </summary>
        /// <param name="vEN_ID">Valor inicial de la propiedad VEN_ID.</param>
        /// <param name="vEN_INICIAL">Valor inicial de la propiedad VEN_INICIAL.</param>
        /// <param name="vEN_FONO">Valor inicial de la propiedad VEN_FONO.</param>
        /// <param name="uSR_ID">Valor inicial de la propiedad USR_ID.</param>
        /// <param name="vEN_UN_ID">Valor inicial de la propiedad VEN_UN_ID.</param>
        public static TBL_VENDEDOR CreateTBL_VENDEDOR(global::System.Decimal vEN_ID, global::System.String vEN_INICIAL, global::System.String vEN_FONO, global::System.Decimal uSR_ID, global::System.String vEN_UN_ID)
        {
            TBL_VENDEDOR tBL_VENDEDOR = new TBL_VENDEDOR();
            tBL_VENDEDOR.VEN_ID = vEN_ID;
            tBL_VENDEDOR.VEN_INICIAL = vEN_INICIAL;
            tBL_VENDEDOR.VEN_FONO = vEN_FONO;
            tBL_VENDEDOR.USR_ID = uSR_ID;
            tBL_VENDEDOR.VEN_UN_ID = vEN_UN_ID;
            return tBL_VENDEDOR;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal VEN_ID
        {
            get
            {
                return _VEN_ID;
            }
            set
            {
                if (_VEN_ID != value)
                {
                    OnVEN_IDChanging(value);
                    ReportPropertyChanging("VEN_ID");
                    _VEN_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VEN_ID");
                    OnVEN_IDChanged();
                }
            }
        }
        private global::System.Decimal _VEN_ID;
        partial void OnVEN_IDChanging(global::System.Decimal value);
        partial void OnVEN_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VEN_INICIAL
        {
            get
            {
                return _VEN_INICIAL;
            }
            set
            {
                OnVEN_INICIALChanging(value);
                ReportPropertyChanging("VEN_INICIAL");
                _VEN_INICIAL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VEN_INICIAL");
                OnVEN_INICIALChanged();
            }
        }
        private global::System.String _VEN_INICIAL;
        partial void OnVEN_INICIALChanging(global::System.String value);
        partial void OnVEN_INICIALChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VEN_FONO
        {
            get
            {
                return _VEN_FONO;
            }
            set
            {
                OnVEN_FONOChanging(value);
                ReportPropertyChanging("VEN_FONO");
                _VEN_FONO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VEN_FONO");
                OnVEN_FONOChanged();
            }
        }
        private global::System.String _VEN_FONO;
        partial void OnVEN_FONOChanging(global::System.String value);
        partial void OnVEN_FONOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] VEN_FIRMA
        {
            get
            {
                return StructuralObject.GetValidValue(_VEN_FIRMA);
            }
            set
            {
                OnVEN_FIRMAChanging(value);
                ReportPropertyChanging("VEN_FIRMA");
                _VEN_FIRMA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VEN_FIRMA");
                OnVEN_FIRMAChanged();
            }
        }
        private global::System.Byte[] _VEN_FIRMA;
        partial void OnVEN_FIRMAChanging(global::System.Byte[] value);
        partial void OnVEN_FIRMAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_ID
        {
            get
            {
                return _USR_ID;
            }
            set
            {
                OnUSR_IDChanging(value);
                ReportPropertyChanging("USR_ID");
                _USR_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_ID");
                OnUSR_IDChanged();
            }
        }
        private global::System.Decimal _USR_ID;
        partial void OnUSR_IDChanging(global::System.Decimal value);
        partial void OnUSR_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VEN_UN_ID
        {
            get
            {
                return _VEN_UN_ID;
            }
            set
            {
                OnVEN_UN_IDChanging(value);
                ReportPropertyChanging("VEN_UN_ID");
                _VEN_UN_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VEN_UN_ID");
                OnVEN_UN_IDChanged();
            }
        }
        private global::System.String _VEN_UN_ID;
        partial void OnVEN_UN_IDChanging(global::System.String value);
        partial void OnVEN_UN_IDChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModelManCalCbo", "TBL_VEN_TBL_USR_FK", "TBL_USUARIO")]
        public TBL_USUARIO TBL_USUARIO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_VEN_TBL_USR_FK", "TBL_USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_VEN_TBL_USR_FK", "TBL_USUARIO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TBL_USUARIO> TBL_USUARIOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_VEN_TBL_USR_FK", "TBL_USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TBL_USUARIO>("ModelManCalCbo.TBL_VEN_TBL_USR_FK", "TBL_USUARIO", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
