//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANCAL_WEB_BL.ManCal_Cbo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCotizacion", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoCotizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_tipocotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_tipocotField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_tipocot {
            get {
                return this.id_tipocotField;
            }
            set {
                if ((this.id_tipocotField.Equals(value) != true)) {
                    this.id_tipocotField = value;
                    this.RaisePropertyChanged("id_tipocot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_tipocot {
            get {
                return this.nom_tipocotField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_tipocotField, value) != true)) {
                    this.nom_tipocotField = value;
                    this.RaisePropertyChanged("nom_tipocot");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vendedor", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class Vendedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_ventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_ventaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_venta {
            get {
                return this.id_ventaField;
            }
            set {
                if ((this.id_ventaField.Equals(value) != true)) {
                    this.id_ventaField = value;
                    this.RaisePropertyChanged("id_venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_venta {
            get {
                return this.nom_ventaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_ventaField, value) != true)) {
                    this.nom_ventaField = value;
                    this.RaisePropertyChanged("nom_venta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTarifa", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoTarifa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_tarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_tarifaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_tarifa {
            get {
                return this.id_tarifaField;
            }
            set {
                if ((this.id_tarifaField.Equals(value) != true)) {
                    this.id_tarifaField = value;
                    this.RaisePropertyChanged("id_tarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_tarifa {
            get {
                return this.nom_tarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_tarifaField, value) != true)) {
                    this.nom_tarifaField = value;
                    this.RaisePropertyChanged("nom_tarifa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTrabajo", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoTrabajo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_trabajoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_trabajoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_trabajo {
            get {
                return this.idn_trabajoField;
            }
            set {
                if ((this.idn_trabajoField.Equals(value) != true)) {
                    this.idn_trabajoField = value;
                    this.RaisePropertyChanged("idn_trabajo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_trabajo {
            get {
                return this.nom_trabajoField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_trabajoField, value) != true)) {
                    this.nom_trabajoField = value;
                    this.RaisePropertyChanged("nom_trabajo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoFactura", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoFactura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_facturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_facturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_factura {
            get {
                return this.idn_facturaField;
            }
            set {
                if ((this.idn_facturaField.Equals(value) != true)) {
                    this.idn_facturaField = value;
                    this.RaisePropertyChanged("idn_factura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_factura {
            get {
                return this.nom_facturaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_facturaField, value) != true)) {
                    this.nom_facturaField = value;
                    this.RaisePropertyChanged("nom_factura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPagoFactura", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoPagoFactura : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_pagofacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_pagofacturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_pagofactura {
            get {
                return this.idn_pagofacturaField;
            }
            set {
                if ((this.idn_pagofacturaField.Equals(value) != true)) {
                    this.idn_pagofacturaField = value;
                    this.RaisePropertyChanged("idn_pagofactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_pagofactura {
            get {
                return this.nom_pagofacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_pagofacturaField, value) != true)) {
                    this.nom_pagofacturaField = value;
                    this.RaisePropertyChanged("nom_pagofactura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPlazoEntregaFac", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoPlazoEntregaFac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_plazoentregafacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_plazoentregafacField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_plazoentregafac {
            get {
                return this.idn_plazoentregafacField;
            }
            set {
                if ((this.idn_plazoentregafacField.Equals(value) != true)) {
                    this.idn_plazoentregafacField = value;
                    this.RaisePropertyChanged("idn_plazoentregafac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_plazoentregafac {
            get {
                return this.nom_plazoentregafacField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_plazoentregafacField, value) != true)) {
                    this.nom_plazoentregafacField = value;
                    this.RaisePropertyChanged("nom_plazoentregafac");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoLugarEjec", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoLugarEjec : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_lugarejecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_lugarejecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_lugarejec {
            get {
                return this.idn_lugarejecField;
            }
            set {
                if ((this.idn_lugarejecField.Equals(value) != true)) {
                    this.idn_lugarejecField = value;
                    this.RaisePropertyChanged("idn_lugarejec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_lugarejec {
            get {
                return this.nom_lugarejecField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_lugarejecField, value) != true)) {
                    this.nom_lugarejecField = value;
                    this.RaisePropertyChanged("nom_lugarejec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoLugarEntr", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoLugarEntr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_lugarentrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_lugarentrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_lugarentr {
            get {
                return this.idn_lugarentrField;
            }
            set {
                if ((this.idn_lugarentrField.Equals(value) != true)) {
                    this.idn_lugarentrField = value;
                    this.RaisePropertyChanged("idn_lugarentr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_lugarentr {
            get {
                return this.nom_lugarentrField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_lugarentrField, value) != true)) {
                    this.nom_lugarentrField = value;
                    this.RaisePropertyChanged("nom_lugarentr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoGarantia", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoGarantia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_garantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_garantiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_garantia {
            get {
                return this.idn_garantiaField;
            }
            set {
                if ((this.idn_garantiaField.Equals(value) != true)) {
                    this.idn_garantiaField = value;
                    this.RaisePropertyChanged("idn_garantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_garantia {
            get {
                return this.nom_garantiaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_garantiaField, value) != true)) {
                    this.nom_garantiaField = value;
                    this.RaisePropertyChanged("nom_garantia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoGarantiaVal", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoGarantiaVal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_garantiavalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_garantiavalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_garantiaval {
            get {
                return this.idn_garantiavalField;
            }
            set {
                if ((this.idn_garantiavalField.Equals(value) != true)) {
                    this.idn_garantiavalField = value;
                    this.RaisePropertyChanged("idn_garantiaval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_garantiaval {
            get {
                return this.nom_garantiavalField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_garantiavalField, value) != true)) {
                    this.nom_garantiavalField = value;
                    this.RaisePropertyChanged("nom_garantiaval");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jefe", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class Jefe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string car_jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mai_jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_jefeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string car_jefe {
            get {
                return this.car_jefeField;
            }
            set {
                if ((object.ReferenceEquals(this.car_jefeField, value) != true)) {
                    this.car_jefeField = value;
                    this.RaisePropertyChanged("car_jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_jefe {
            get {
                return this.idn_jefeField;
            }
            set {
                if ((this.idn_jefeField.Equals(value) != true)) {
                    this.idn_jefeField = value;
                    this.RaisePropertyChanged("idn_jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mai_jefe {
            get {
                return this.mai_jefeField;
            }
            set {
                if ((object.ReferenceEquals(this.mai_jefeField, value) != true)) {
                    this.mai_jefeField = value;
                    this.RaisePropertyChanged("mai_jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_jefe {
            get {
                return this.nom_jefeField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_jefeField, value) != true)) {
                    this.nom_jefeField = value;
                    this.RaisePropertyChanged("nom_jefe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Region", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class Region : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_regionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_regionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_region {
            get {
                return this.idn_regionField;
            }
            set {
                if ((this.idn_regionField.Equals(value) != true)) {
                    this.idn_regionField = value;
                    this.RaisePropertyChanged("idn_region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_region {
            get {
                return this.nom_regionField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_regionField, value) != true)) {
                    this.nom_regionField = value;
                    this.RaisePropertyChanged("nom_region");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEnvio", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class TipoEnvio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_tipoenvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_tipoenvioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_tipoenvio {
            get {
                return this.idn_tipoenvioField;
            }
            set {
                if ((this.idn_tipoenvioField.Equals(value) != true)) {
                    this.idn_tipoenvioField = value;
                    this.RaisePropertyChanged("idn_tipoenvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_tipoenvio {
            get {
                return this.nom_tipoenvioField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_tipoenvioField, value) != true)) {
                    this.nom_tipoenvioField = value;
                    this.RaisePropertyChanged("nom_tipoenvio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lugar", Namespace="http://schemas.datacontract.org/2004/07/MANCAL_WCF_CBO")]
    [System.SerializableAttribute()]
    public partial class Lugar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idn_lugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_lugarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idn_lugar {
            get {
                return this.idn_lugarField;
            }
            set {
                if ((this.idn_lugarField.Equals(value) != true)) {
                    this.idn_lugarField = value;
                    this.RaisePropertyChanged("idn_lugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_lugar {
            get {
                return this.nom_lugarField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_lugarField, value) != true)) {
                    this.nom_lugarField = value;
                    this.RaisePropertyChanged("nom_lugar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManCal_Cbo.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsTipoCotizacionMan", ReplyAction="http://tempuri.org/IService/lsTipoCotizacionManResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoCotizacion[] lsTipoCotizacionMan(string id_un);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsVendedor", ReplyAction="http://tempuri.org/IService/lsVendedorResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.Vendedor[] lsVendedor(string id_un);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsTarifa", ReplyAction="http://tempuri.org/IService/lsTarifaResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoTarifa[] lsTarifa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsTrabajo", ReplyAction="http://tempuri.org/IService/lsTrabajoResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoTrabajo[] lsTrabajo(string un, string forma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsFactura", ReplyAction="http://tempuri.org/IService/lsFacturaResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoFactura[] lsFactura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsPagoFactura", ReplyAction="http://tempuri.org/IService/lsPagoFacturaResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoPagoFactura[] lsPagoFactura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsPlazoEntregaFac", ReplyAction="http://tempuri.org/IService/lsPlazoEntregaFacResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoPlazoEntregaFac[] lsPlazoEntregaFac();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsLugarEjec", ReplyAction="http://tempuri.org/IService/lsLugarEjecResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoLugarEjec[] lsLugarEjec();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsLugarEntr", ReplyAction="http://tempuri.org/IService/lsLugarEntrResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoLugarEntr[] lsLugarEntr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsGarantia", ReplyAction="http://tempuri.org/IService/lsGarantiaResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoGarantia[] lsGarantia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsGarantiaVal", ReplyAction="http://tempuri.org/IService/lsGarantiaValResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoGarantiaVal[] lsGarantiaVal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsJefe", ReplyAction="http://tempuri.org/IService/lsJefeResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.Jefe[] lsJefe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/datosJefe", ReplyAction="http://tempuri.org/IService/datosJefeResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.Jefe datosJefe(decimal id_jefe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsRegion", ReplyAction="http://tempuri.org/IService/lsRegionResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.Region[] lsRegion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsEnvio", ReplyAction="http://tempuri.org/IService/lsEnvioResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.TipoEnvio[] lsEnvio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/lsLugar", ReplyAction="http://tempuri.org/IService/lsLugarResponse")]
        MANCAL_WEB_BL.ManCal_Cbo.Lugar[] lsLugar();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MANCAL_WEB_BL.ManCal_Cbo.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MANCAL_WEB_BL.ManCal_Cbo.IService>, MANCAL_WEB_BL.ManCal_Cbo.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoCotizacion[] lsTipoCotizacionMan(string id_un) {
            return base.Channel.lsTipoCotizacionMan(id_un);
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.Vendedor[] lsVendedor(string id_un) {
            return base.Channel.lsVendedor(id_un);
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoTarifa[] lsTarifa() {
            return base.Channel.lsTarifa();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoTrabajo[] lsTrabajo(string un, string forma) {
            return base.Channel.lsTrabajo(un, forma);
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoFactura[] lsFactura() {
            return base.Channel.lsFactura();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoPagoFactura[] lsPagoFactura() {
            return base.Channel.lsPagoFactura();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoPlazoEntregaFac[] lsPlazoEntregaFac() {
            return base.Channel.lsPlazoEntregaFac();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoLugarEjec[] lsLugarEjec() {
            return base.Channel.lsLugarEjec();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoLugarEntr[] lsLugarEntr() {
            return base.Channel.lsLugarEntr();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoGarantia[] lsGarantia() {
            return base.Channel.lsGarantia();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoGarantiaVal[] lsGarantiaVal() {
            return base.Channel.lsGarantiaVal();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.Jefe[] lsJefe() {
            return base.Channel.lsJefe();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.Jefe datosJefe(decimal id_jefe) {
            return base.Channel.datosJefe(id_jefe);
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.Region[] lsRegion() {
            return base.Channel.lsRegion();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.TipoEnvio[] lsEnvio() {
            return base.Channel.lsEnvio();
        }
        
        public MANCAL_WEB_BL.ManCal_Cbo.Lugar[] lsLugar() {
            return base.Channel.lsLugar();
        }
    }
}
