//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANCAL_WEB.ServiceEncripta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Encripta_ws", ConfigurationName="ServiceEncripta.Encripta_wsSOAPPortType")]
    public interface Encripta_wsSOAPPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación Encripta no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Encripta_ws/Encripta", ReplyAction="*")]
        MANCAL_WEB.ServiceEncripta.EncriptaResponse Encripta(MANCAL_WEB.ServiceEncripta.EncriptaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string valor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public EncriptaRequest() {
        }
        
        public EncriptaRequest(string valor, string password) {
            this.valor = valor;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncriptaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string EncriptaResult;
        
        public EncriptaResponse() {
        }
        
        public EncriptaResponse(string EncriptaResult) {
            this.EncriptaResult = EncriptaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Encripta_wsSOAPPortTypeChannel : MANCAL_WEB.ServiceEncripta.Encripta_wsSOAPPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Encripta_wsSOAPPortTypeClient : System.ServiceModel.ClientBase<MANCAL_WEB.ServiceEncripta.Encripta_wsSOAPPortType>, MANCAL_WEB.ServiceEncripta.Encripta_wsSOAPPortType {
        
        public Encripta_wsSOAPPortTypeClient() {
        }
        
        public Encripta_wsSOAPPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Encripta_wsSOAPPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Encripta_wsSOAPPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Encripta_wsSOAPPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MANCAL_WEB.ServiceEncripta.EncriptaResponse MANCAL_WEB.ServiceEncripta.Encripta_wsSOAPPortType.Encripta(MANCAL_WEB.ServiceEncripta.EncriptaRequest request) {
            return base.Channel.Encripta(request);
        }
        
        public string Encripta(string valor, string password) {
            MANCAL_WEB.ServiceEncripta.EncriptaRequest inValue = new MANCAL_WEB.ServiceEncripta.EncriptaRequest();
            inValue.valor = valor;
            inValue.password = password;
            MANCAL_WEB.ServiceEncripta.EncriptaResponse retVal = ((MANCAL_WEB.ServiceEncripta.Encripta_wsSOAPPortType)(this)).Encripta(inValue);
            return retVal.EncriptaResult;
        }
    }
}
