//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ModelManCal
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EntitiesManCal : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EntitiesManCal usando la cadena de conexión encontrada en la sección 'EntitiesManCal' del archivo de configuración de la aplicación.
        /// </summary>
        public EntitiesManCal() : base("name=EntitiesManCal", "EntitiesManCal")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntitiesManCal.
        /// </summary>
        public EntitiesManCal(string connectionString) : base(connectionString, "EntitiesManCal")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EntitiesManCal.
        /// </summary>
        public EntitiesManCal(EntityConnection connection) : base(connection, "EntitiesManCal")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_USUARIO> TBL_USUARIO
        {
            get
            {
                if ((_TBL_USUARIO == null))
                {
                    _TBL_USUARIO = base.CreateObjectSet<TBL_USUARIO>("TBL_USUARIO");
                }
                return _TBL_USUARIO;
            }
        }
        private ObjectSet<TBL_USUARIO> _TBL_USUARIO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TBL_MENU> TBL_MENU
        {
            get
            {
                if ((_TBL_MENU == null))
                {
                    _TBL_MENU = base.CreateObjectSet<TBL_MENU>("TBL_MENU");
                }
                return _TBL_MENU;
            }
        }
        private ObjectSet<TBL_MENU> _TBL_MENU;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_USUARIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_USUARIO(TBL_USUARIO tBL_USUARIO)
        {
            base.AddObject("TBL_USUARIO", tBL_USUARIO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TBL_MENU. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTBL_MENU(TBL_MENU tBL_MENU)
        {
            base.AddObject("TBL_MENU", tBL_MENU);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCal", Name="TBL_MENU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_MENU : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_MENU.
        /// </summary>
        /// <param name="mENU_ID">Valor inicial de la propiedad MENU_ID.</param>
        /// <param name="mENU_NOMBRE">Valor inicial de la propiedad MENU_NOMBRE.</param>
        /// <param name="mENU_GRUPO">Valor inicial de la propiedad MENU_GRUPO.</param>
        public static TBL_MENU CreateTBL_MENU(global::System.Decimal mENU_ID, global::System.String mENU_NOMBRE, global::System.Decimal mENU_GRUPO)
        {
            TBL_MENU tBL_MENU = new TBL_MENU();
            tBL_MENU.MENU_ID = mENU_ID;
            tBL_MENU.MENU_NOMBRE = mENU_NOMBRE;
            tBL_MENU.MENU_GRUPO = mENU_GRUPO;
            return tBL_MENU;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MENU_ID
        {
            get
            {
                return _MENU_ID;
            }
            set
            {
                if (_MENU_ID != value)
                {
                    OnMENU_IDChanging(value);
                    ReportPropertyChanging("MENU_ID");
                    _MENU_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MENU_ID");
                    OnMENU_IDChanged();
                }
            }
        }
        private global::System.Decimal _MENU_ID;
        partial void OnMENU_IDChanging(global::System.Decimal value);
        partial void OnMENU_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MENU_NOMBRE
        {
            get
            {
                return _MENU_NOMBRE;
            }
            set
            {
                OnMENU_NOMBREChanging(value);
                ReportPropertyChanging("MENU_NOMBRE");
                _MENU_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MENU_NOMBRE");
                OnMENU_NOMBREChanged();
            }
        }
        private global::System.String _MENU_NOMBRE;
        partial void OnMENU_NOMBREChanging(global::System.String value);
        partial void OnMENU_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MENU_GRUPO
        {
            get
            {
                return _MENU_GRUPO;
            }
            set
            {
                OnMENU_GRUPOChanging(value);
                ReportPropertyChanging("MENU_GRUPO");
                _MENU_GRUPO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MENU_GRUPO");
                OnMENU_GRUPOChanged();
            }
        }
        private global::System.Decimal _MENU_GRUPO;
        partial void OnMENU_GRUPOChanging(global::System.Decimal value);
        partial void OnMENU_GRUPOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MENU_FUNCU
        {
            get
            {
                return _MENU_FUNCU;
            }
            set
            {
                OnMENU_FUNCUChanging(value);
                ReportPropertyChanging("MENU_FUNCU");
                _MENU_FUNCU = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MENU_FUNCU");
                OnMENU_FUNCUChanged();
            }
        }
        private Nullable<global::System.Decimal> _MENU_FUNCU;
        partial void OnMENU_FUNCUChanging(Nullable<global::System.Decimal> value);
        partial void OnMENU_FUNCUChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MENU_FUNCD
        {
            get
            {
                return _MENU_FUNCD;
            }
            set
            {
                OnMENU_FUNCDChanging(value);
                ReportPropertyChanging("MENU_FUNCD");
                _MENU_FUNCD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MENU_FUNCD");
                OnMENU_FUNCDChanged();
            }
        }
        private Nullable<global::System.Decimal> _MENU_FUNCD;
        partial void OnMENU_FUNCDChanging(Nullable<global::System.Decimal> value);
        partial void OnMENU_FUNCDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MENU_FUNCT
        {
            get
            {
                return _MENU_FUNCT;
            }
            set
            {
                OnMENU_FUNCTChanging(value);
                ReportPropertyChanging("MENU_FUNCT");
                _MENU_FUNCT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MENU_FUNCT");
                OnMENU_FUNCTChanged();
            }
        }
        private Nullable<global::System.Decimal> _MENU_FUNCT;
        partial void OnMENU_FUNCTChanging(Nullable<global::System.Decimal> value);
        partial void OnMENU_FUNCTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MENU_FUNCC
        {
            get
            {
                return _MENU_FUNCC;
            }
            set
            {
                OnMENU_FUNCCChanging(value);
                ReportPropertyChanging("MENU_FUNCC");
                _MENU_FUNCC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MENU_FUNCC");
                OnMENU_FUNCCChanged();
            }
        }
        private Nullable<global::System.Decimal> _MENU_FUNCC;
        partial void OnMENU_FUNCCChanging(Nullable<global::System.Decimal> value);
        partial void OnMENU_FUNCCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MENU_URL
        {
            get
            {
                return _MENU_URL;
            }
            set
            {
                OnMENU_URLChanging(value);
                ReportPropertyChanging("MENU_URL");
                _MENU_URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MENU_URL");
                OnMENU_URLChanged();
            }
        }
        private global::System.String _MENU_URL;
        partial void OnMENU_URLChanging(global::System.String value);
        partial void OnMENU_URLChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModelManCal", Name="TBL_USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TBL_USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TBL_USUARIO.
        /// </summary>
        /// <param name="uSR_ID">Valor inicial de la propiedad USR_ID.</param>
        /// <param name="uSR_NOMBRE">Valor inicial de la propiedad USR_NOMBRE.</param>
        /// <param name="uSR_APPAT">Valor inicial de la propiedad USR_APPAT.</param>
        /// <param name="uSR_APMAT">Valor inicial de la propiedad USR_APMAT.</param>
        /// <param name="uSR_USRPC">Valor inicial de la propiedad USR_USRPC.</param>
        /// <param name="uSR_PWD">Valor inicial de la propiedad USR_PWD.</param>
        /// <param name="uSR_PERFIL">Valor inicial de la propiedad USR_PERFIL.</param>
        /// <param name="uSR_ESTADO">Valor inicial de la propiedad USR_ESTADO.</param>
        public static TBL_USUARIO CreateTBL_USUARIO(global::System.Decimal uSR_ID, global::System.String uSR_NOMBRE, global::System.String uSR_APPAT, global::System.String uSR_APMAT, global::System.String uSR_USRPC, global::System.String uSR_PWD, global::System.Decimal uSR_PERFIL, global::System.Decimal uSR_ESTADO)
        {
            TBL_USUARIO tBL_USUARIO = new TBL_USUARIO();
            tBL_USUARIO.USR_ID = uSR_ID;
            tBL_USUARIO.USR_NOMBRE = uSR_NOMBRE;
            tBL_USUARIO.USR_APPAT = uSR_APPAT;
            tBL_USUARIO.USR_APMAT = uSR_APMAT;
            tBL_USUARIO.USR_USRPC = uSR_USRPC;
            tBL_USUARIO.USR_PWD = uSR_PWD;
            tBL_USUARIO.USR_PERFIL = uSR_PERFIL;
            tBL_USUARIO.USR_ESTADO = uSR_ESTADO;
            return tBL_USUARIO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_ID
        {
            get
            {
                return _USR_ID;
            }
            set
            {
                if (_USR_ID != value)
                {
                    OnUSR_IDChanging(value);
                    ReportPropertyChanging("USR_ID");
                    _USR_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("USR_ID");
                    OnUSR_IDChanged();
                }
            }
        }
        private global::System.Decimal _USR_ID;
        partial void OnUSR_IDChanging(global::System.Decimal value);
        partial void OnUSR_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_NOMBRE
        {
            get
            {
                return _USR_NOMBRE;
            }
            set
            {
                OnUSR_NOMBREChanging(value);
                ReportPropertyChanging("USR_NOMBRE");
                _USR_NOMBRE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_NOMBRE");
                OnUSR_NOMBREChanged();
            }
        }
        private global::System.String _USR_NOMBRE;
        partial void OnUSR_NOMBREChanging(global::System.String value);
        partial void OnUSR_NOMBREChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_APPAT
        {
            get
            {
                return _USR_APPAT;
            }
            set
            {
                OnUSR_APPATChanging(value);
                ReportPropertyChanging("USR_APPAT");
                _USR_APPAT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_APPAT");
                OnUSR_APPATChanged();
            }
        }
        private global::System.String _USR_APPAT;
        partial void OnUSR_APPATChanging(global::System.String value);
        partial void OnUSR_APPATChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_APMAT
        {
            get
            {
                return _USR_APMAT;
            }
            set
            {
                OnUSR_APMATChanging(value);
                ReportPropertyChanging("USR_APMAT");
                _USR_APMAT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_APMAT");
                OnUSR_APMATChanged();
            }
        }
        private global::System.String _USR_APMAT;
        partial void OnUSR_APMATChanging(global::System.String value);
        partial void OnUSR_APMATChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_USRPC
        {
            get
            {
                return _USR_USRPC;
            }
            set
            {
                OnUSR_USRPCChanging(value);
                ReportPropertyChanging("USR_USRPC");
                _USR_USRPC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_USRPC");
                OnUSR_USRPCChanged();
            }
        }
        private global::System.String _USR_USRPC;
        partial void OnUSR_USRPCChanging(global::System.String value);
        partial void OnUSR_USRPCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USR_PWD
        {
            get
            {
                return _USR_PWD;
            }
            set
            {
                OnUSR_PWDChanging(value);
                ReportPropertyChanging("USR_PWD");
                _USR_PWD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("USR_PWD");
                OnUSR_PWDChanged();
            }
        }
        private global::System.String _USR_PWD;
        partial void OnUSR_PWDChanging(global::System.String value);
        partial void OnUSR_PWDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_PERFIL
        {
            get
            {
                return _USR_PERFIL;
            }
            set
            {
                OnUSR_PERFILChanging(value);
                ReportPropertyChanging("USR_PERFIL");
                _USR_PERFIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_PERFIL");
                OnUSR_PERFILChanged();
            }
        }
        private global::System.Decimal _USR_PERFIL;
        partial void OnUSR_PERFILChanging(global::System.Decimal value);
        partial void OnUSR_PERFILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal USR_ESTADO
        {
            get
            {
                return _USR_ESTADO;
            }
            set
            {
                OnUSR_ESTADOChanging(value);
                ReportPropertyChanging("USR_ESTADO");
                _USR_ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("USR_ESTADO");
                OnUSR_ESTADOChanged();
            }
        }
        private global::System.Decimal _USR_ESTADO;
        partial void OnUSR_ESTADOChanging(global::System.Decimal value);
        partial void OnUSR_ESTADOChanged();

        #endregion

    
    }

    #endregion

    
}
